[package]
name = "yyjson-sys"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"
license = "MIT"
description = "Raw bindings to yyjson"

[dependencies]

[build-dependencies]
cc = "1.0.61"
bindgen = "0.55.1"
